"""Knowledge base: AI Q&A during sessions + Markdown export to vault."""

from __future__ import annotations

from datetime import datetime
import uuid
import pathlib
from models import KnowledgeEntry
import state


def create_qa_entry(session_id: str, task_id: str, question: str,
                    answer: str, summary: str = "") -> dict:
    if not summary:
        summary = answer[:200] + "..." if len(answer) > 200 else answer
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    md_filename = f"qa_{ts}_{str(uuid.uuid4())[:8]}.md"
    vault_dir = state.get_vault_dir()
    md_path = vault_dir / md_filename
    entry = KnowledgeEntry(
        session_id=session_id,
        task_id=task_id,
        question=question,
        answer=answer,
        summary=summary,
        markdown_path=str(md_path),
    )
    _save_markdown(entry)
    entry_dict = entry.to_dict()
    state.save_knowledge_entry(entry_dict)
    state.log_action("knowledge_save", f"Q: {question[:50]}... -> {md_filename}")
    return entry_dict


def _save_markdown(entry: KnowledgeEntry) -> None:
    content = f"""# AI Knowledge Entry

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Session:** {entry.session_id[:8] if entry.session_id else 'N/A'}
**Task:** {entry.task_id[:8] if entry.task_id else 'N/A'}

## Question

{entry.question}

## Answer

{entry.answer}

## Summary

{entry.summary}

---

*Auto-generated by SmartFocus*
"""
    pathlib.Path(entry.markdown_path).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(entry.markdown_path).write_text(content, encoding="utf-8")


def get_knowledge_entries(limit: int = 50) -> list[dict]:
    return state.get_knowledge_entries(limit)


def generate_synthetic_answer(question: str, task_title: str = "") -> str:
    return (
        f"Regarding '{question}':\n\n"
        f"Based on task '{task_title}', here's a synthesized answer:\n\n"
        f"1. This is a demo answer from SmartFocus's knowledge module.\n"
        f"2. In production, an actual LLM response replaces this.\n"
        f"3. The answer is linked to the current task and saved to the vault.\n\n"
        f"Key points:\n"
        f"- Break down the problem into smaller steps\n"
        f"- Focus on one sub-task at a time\n"
        f"- Use the Pomodoro timer to maintain focus\n"
    )
